version: '3.8'

services:
  nginx:
    image: nginx:1.21.6
    container_name: polymarket-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf.d/polymarket-dev-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./www:/var/www/html
    networks:
      polymarket-network:
        aliases: 
          - nginx.polymarket.kr
  certbot:
    image: certbot/certbot:v1.27.0
    container_name: polymarket-certbot
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/var:/var/lib/certbot
      - ./www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sinwoo1225@gmail.com --agree-tos --no-eff-email --force-renewal -d polymarket.kr -d www.polymarket.kr -d jenkins-dev.polymarket.kr -d front-dev.polymarket.kr -d api-dev.polymarket.kr
    depends_on:
      - nginx
  front:
    image: polymarket-front:local
    container_name: polymarket-front
    hostname: front-dev.polymarket.kr
    networks:
      polymarket-network:
        aliases: 
          - front-dev.polymarket.kr
  jenkins:
    image: jenkins/jenkins:latest-jdk11
    container_name: polymarket-jenkins
    hostname: jenkins-dev.polymarket.kr
    volumes:
      - /home/polymarket/jenkins:/var/jenkins_home
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    networks:
      polymarket-network:
        aliases: 
          - jenkins-dev.polymarket.kr
  api:
    image: polymarket-api:local
    container_name: polymarket-api
    hostname: api-dev.polymarket.kr
    environment: 
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      polymarket-network:
  config-server:
    image: polymarket-config-server:local
    container_name: config-server
    hostname: config-dev.polymarket.kr
    environment: 
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      polymarket-network:
  mysql:
    image: mysql:8.0.29
    container_name: polymarket-mysql
    hostname: mysql-dev.polymarket.kr
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: polymarket1!
      TZ: Asia/Seoul
    volumes:
      - /home/polymarket/mysql:/var/lib/mysql 
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      polymarket-network:
        aliases: 
          - mysql-dev.polymarket.kr
  redis:
    image: redis:7.0.0
    container_name: polymarket-redis
    hostname: redis-dev.polymarket.kr
    ports:
      - 6379:6379
    restart: always
    volumes:
      - /home/polymarket/redis/data:/data
    networks:
      polymarket-network:
        aliases: 
          - redis-dev.polymarket.kr
  elasticsearch:
    container_name: polymarket-elasticsearch
    build:
      context: ./elasticsearch
    ports:
     - 9200:9200
     - 9300:9300
    volumes:
     - /home/polymarket/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
     - TZ=Asia/Seoul
     - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    networks:
      polymarket-network:
        aliases: 
          - es-dev.polymarket.kr
  logstash:
    container_name: polymarket-logstash
    image: logstash:7.17.3
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
      - xpack.monitoring.enabled=true
      - xpack.monitoring.elasticsearch.hosts=http://es-dev.polymarket.kr
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./logstash/mysql-connector-java-8.0.29.jar:/usr/share/logstash/logstash-core/lib/jar/mysql-connector-java-8.0.29.jar:ro
    command: logstash -f /usr/share/logstash/config/logstash.conf
    depends_on:
      - elasticsearch
      - mysql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    networks:
      polymarket-network:
        aliases: 
          - logstash-dev.polymarket.kr
  kibana:
    container_name: polymarket-kibana
    image: kibana:7.17.3
    ports:
     - 5601:5601
    environment:
     ELASTICSERCH_UTL: http://es-dev.polymarket.kr:9200
     ELASTICSEARCH_HOSTS: http://es-dev.polymarket.kr:9200
     TZ: Asia/Seoul
    restart: always
    depends_on:
      - elasticsearch
    networks:
      polymarket-network:
        aliases: 
          - kibana-dev.polymarket.kr

networks:
  polymarket-network: